language: java
before_install:
-chmod +x gradlew

script:
-./gradlew build --info

before_cashe:
- rm -f $HOME/.gradle/caches/modules-2/modles-2.lock
-rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  
deploy:
  provider: heroku
  api_key:
      secure: 460ebdd9-ea37-4bb0-ae46-edf24ca98493
  app: dimitratut6
  skip_cleanup: true
